services:
  pokedex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokedex-app
    ports:
      - "8100:8100"
      - "35729:35729"
    volumes:
      - .:/app
      - /app/node_modules
