#!/usr/bin/env sh

if ! docker info > /dev/null 2>&1; then
    echo "❌ Docker não está rodando. Inicie o Docker e tente novamente."
    exit 1
fi

if ! docker compose exec -T pokedex npm run format:check; then
    docker compose exec -T pokedex npm run format
    if [ $? -ne 0 ]; then
        echo "Opa! Deu ruim aqui com Prittier. Arrume antes de continuar... 😉";
        exit 1;
    fi;

    STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(ts|html|css|scss|json)$" || true)
    for FILE in $STAGED_FILES; do
        [ -f "$FILE" ] && git add "$FILE"
    done
fi

docker compose exec -T pokedex npm run lint
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com Lint. Arrume antes de continuar... 😉";
    exit 1;
fi;

docker compose exec -T pokedex npm run test
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com Jest. Arrume antes de continuar... 😉";
    exit 1;
fi;

exit 0;
